apiVersion: v1
kind: Secret
metadata:
  name: sql-secret
type: Opaque

stringData:

  DB_SERVER: sqlservercarlos69.database.windows.net
  DB_NAME: productosdb
  DB_USER: sqladmin
  DB_PASSWORD: Password1234!